apiVersion: v1
kind: Secret
metadata:
  name: sparrow-secrets
  namespace: sparrow-vps
type: Opaque
stringData:
  ghClientId: "placeholder" # github client id
  ghClientSecret: "placeholder" # github client secret
  sbApiKey: "placeholder" # supabase api key
  sbDbUrl: "placeholder" # supabase project url
  sbDbPwd: "placeholder" # supabase databse password
  dockerHubUname: "placeholder" # dockerhub username
  dockerHubPasswd: "placeholder" # dockerhub password
