apiVersion: v1
kind: Service
metadata:
  name: container-service-svc
  namespace: sparrow-vps
spec:
  selector:
    app: container-service
  ports:
  - protocol: TCP
    port: 8002
    targetPort: 8002
    nodePort: 30082
  type: NodePort
