apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: deploy-service-crb
subjects:
  - kind: ServiceAccount
    name: deploy-service-sa
    namespace: sparrow-vps
roleRef:
  kind: ClusterRole
  name: deploy-service-crd
  apiGroup: rbac.authorization.k8s.io
