apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deploy-service-crd
rules:
  - apiGroups: ["apps"] # Permissions for Deployments
    resources: ["deployments"]
    verbs: ["create", "get", "update", "patch", "delete", "list", "watch"]
  - apiGroups: [""] # Permissions for Services (core API group)
    resources: ["services"]
    verbs: ["create", "get", "update", "patch", "delete", "list", "watch"]
  - apiGroups: ["networking.k8s.io"] # Permissions for Ingresses
    resources: ["ingresses"]
    verbs: ["create", "get", "update", "patch", "delete", "list", "watch"]
  - apiGroups: [""] # Permissions for Pods (useful for watching status or logs of deployed apps)
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
