apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-service-deployment
  namespace: sparrow-vps
  labels:
    app: deploy-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-service
  template:
    metadata:
      labels:
        app: deploy-service
      annotations:
        prometheus.io/scrape: "true"          # Enable Prometheus scraping
        prometheus.io/path: "/metrics"         # Metrics endpoint path
        prometheus.io/port: "8002"              # Port your app listens on for metrics (matches main.go)
    spec:
      serviceAccountName: deploy-service-sa
      containers:
        - name: deploy-service
          image: r3dacted42/sparrow-deploy-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8002                # Changed to 8002 to match main.go Gin port
          env:
            - name: SPARROW_ORIGIN
              valueFrom:
                configMapKeyRef:
                  name: sparrow-config
                  key: allowedOrigins
