apiVersion: v1
kind: Service
metadata:
  name: deploy-service-svc
  namespace: sparrow-vps
spec:
  selector:
    app: deploy-service
  ports:
  - protocol: TCP
    port: 8002
    targetPort: 8002
    nodePort: 30082
  type: NodePort
